# Generated by Django 4.2 on 2023-04-16 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doner_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doner',
            old_name='Category',
            new_name='Blood_Group',
        ),
        migrations.RenameField(
            model_name='doner',
            old_name='Date',
            new_name='Donated_date',
        ),
        migrations.AddField(
            model_name='doner',
            name='Email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doner',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AddField(
            model_name='doner',
            name='Occupation',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doner',
            name='PhoneNumber',
            field=models.CharField(default=12345, max_length=10),
            preserve_default=False,
        ),
    ]
