# Generated by Django 4.2 on 2023-04-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_doner_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20),
        ),
    ]
