# Generated by Django 4.2 on 2023-04-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_doner_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doner',
            name='Donated_date',
        ),
    ]
