# Generated by Django 4.2 on 2023-05-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_doner_donated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doner',
            old_name='Blood_Group',
            new_name='BloodGroup',
        ),
        migrations.RenameField(
            model_name='doner',
            old_name='Name',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='doner',
            old_name='Occupation',
            new_name='Lname',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='doner',
            name='PhoneNumber',
        ),
    ]
