# Generated by Django 4.2 on 2023-05-01 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_blood_group_doner_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doner',
            name='BloodGroup',
        ),
        migrations.AddField(
            model_name='doner',
            name='Bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
